name: CI

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Set up Android SDK
      uses: actions/setup-android@v1
      with:
        components: platform-tools,tools,build-tools,android-29,extra-google-m2repository,extra-android-m2repository

    - name: Build the app
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test
